image:
  repository: kismia/pushd
  tag: version-0.3.0
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

hostNetwork: true

service:
  type: ClusterIP
  respPort: 20001
  httpPort: 20002
  annotations:
    prometheus.io/scrape: "pushd"
    prometheus.io/port: "20002"

arguments: []
#  - --default-buckets=0.005,0.01,0.025,0.05,0.1,0.25,0.5,1,2.5,5,10

resources:
  limits:
    cpu: 25m
    memory: 64Mi
  requests:
    cpu: 25m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}
