image:
  repository: kismia/pushd
  tag: version-0.2.0
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

# inject env to client pod
# env:
#   - name: PUSHD_HOST
#     valueFrom:
#       fieldRef:
#         fieldPath: status.hostIP
hostNetwork: true

service:
  type: ClusterIP
  respPort: 20001
  httpPort: 20002
  annotations:
    prometheus.io/scrape: "pushd"
    prometheus.io/port: "20002"

resources:
  limits:
    cpu: 25m
    memory: 64Mi
  requests:
    cpu: 25m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}
